showError: Switch to less ancient error reporting
So far, the function calls virConnCopyLastError() which is
suboptimal since we have virGetLastErrorMessage(). Switch to
that.

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
Reviewed-by: Martin Kletzander <mkletzan@redhat.com>