libvirtSnmpError: Introduce and use printSystemError
This function formats passed string and prints stringified system
error.

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
Reviewed-by: Martin Kletzander <mkletzan@redhat.com>